### ISSUE TITLE
About long term

### ISSUE THREAD

**Issue by qiaozhijian** [SJTU-ViSYS/M2DGR#1]
Thank you for your excellent work!

I notice that the sequences, "street 1" and "street 2", are marked with long-term. However, it seems two trajectories are not joint?

By the way, my research topic is about long-term localization. The common datasets I used are Oxford RobotCar and NCLT. In both datasets, different seasons and weathers are also included. One more important thing is that most of their trajectories are overlapped.  In this way, for example, we can localize our robot in the summer on the map built in the winter to evaluate our performance on long-term situation.

**Comment by SJTU-ViSYS** [comment]
I understand what you are trying to express, but in our paper, we define a sequence as "long-term" when its duration is over 20 minutes. Recommend you a paper "Are We Ready for Service Robots? The OpenLORIS-Scene Datasets for
Lifelong SLAM", which focuses on scenarios with large overlap. 

In our dataset, you can find sequences with large overlaps in "Room" ,"Roomdark" and "Hall".

**Comment by qiaozhijian** [comment]
Thank you~
