### ISSUE TITLE
真值问题

### ISSUE THREAD

**Issue by repeeeeeat** [SJTU-ViSYS/M2DGR#100]
您好！我想询问一下关于street_04关于真值的问题。能否提供一下转换坐标系后的真值数据，或者转换方法？因为我在进行对比实验的时候误差非常的大但是轨迹的形状大致一致。十分期待您的回复！很感谢您提供的数据集！

**Comment by bbblobby** [comment]
我也有同样的问题，貌似PPP和PPP/INS解算后的结果与真值差距都非常大，甚至到十几米的差距。数据集十分全面，指导非常详细，也十分期待您的回复！
