### ISSUE TITLE
ros文件转换问题

### ISSUE THREAD

**Issue by imHanna1** [SJTU-ViSYS/M2DGR#102]
您好！请问ros里的GNSS、IMU数据可以提取出来变成.obs和.csv/bin文件进行使用吗？我很想使用这个数据，但是不是基于ROS处理的。

**Comment by sjtuyinjie** [comment]
可以的，但是需要自己写转换脚本，具体请参照CSDN或chatgpt。关于GNSS，更建议使用M2DGR-plus，采集的是ublox zed f9p的数据，相对来说更方便转换一些

**Comment by imHanna1** [comment]
您好，请问您有时间可以回复一下这个问题吗？https://github.com/sjtuyinjie/Sky-GVINS-Dataset/issues/1 我下载了M2DGR的street01bag，好像不是sky-gins的数据。sky-gins链接的bridge1我也下载了，但是里面没有指向天空的图。所以想请问您sky-gins的数据是哪个呢。感谢。
