### ISSUE TITLE
Does the GT in the Dataset Refer to Xsens Sensors or Other Sensors?

### ISSUE THREAD

**Issue by Hanhui-Liu** [SJTU-ViSYS/M2DGR#107]
Does the GT in the dataset refer to Xsens sensors or other sensors?

**Comment by sjtuyinjie** [comment]
In all outdoor scenes, the GT frame refer to the Xsens frame.

**Comment by HariPrasanth-SM** [comment]
What about the indoor scenes? What is the GT frame reference in indoor testcases (in rooms and halls)?
