### ISSUE TITLE
Fail to Download Rosbags

### ISSUE THREAD

**Issue by dwbzxc** [SJTU-ViSYS/M2DGR#11]
Hi, thanks for your great work first.
I failed to download the "alternative indoors and outdoors" rosbags from the provided link. But I could download the ".txt" format ground truth files successfully.
Do you have any ideas how to fix it?
Thank you!

**Comment by sjtuyinjie** [comment]
Sorry for late reply. That might be a network problem. Have you tried to download this via campus network?

**Comment by dwbzxc** [comment]
I tried to download this via campus network and it succeeded. Thank you!
