### ISSUE TITLE
请问真值中的意义

### ISSUE THREAD

**Issue by ChengYueQ** [SJTU-ViSYS/M2DGR#13]
请问真值中的x,y,z具体怎么来的呢，照道理来说z的值应该都差不多才对，但是我显示出来轨迹都是倾斜的
```
evo_traj tum gate_01.txt -p
```
![2022-03-11 15-58-13 的屏幕截图](https://user-images.githubusercontent.com/45324807/157828290-b492443b-0ea8-4cc3-b5b1-ca3b22bd6cbe.png)

**Comment by sjtuyinjie** [comment]
The coordinates of our GT files in the outdoor environments are not in the ENU frame, but the ECEF frame.
