### ISSUE TITLE
Can you please provide the extrinsic information between VI-sensor and Handsfree IMU?

### ISSUE THREAD

**Issue by h-k8888** [SJTU-ViSYS/M2DGR#14]
and the extrinsic information between VI-sensor and LiDAR,
Thanks.

**Comment by h-k8888** [comment]
I test VINS-MONO noloop using Cam-pinhole-color realsense d435i with Handsfree IMU, the ape is worse than  Cam-pinhole-color realsense d435i with buildin IMU, do you know why?
![camera handsfree](https://user-images.githubusercontent.com/68782862/158758427-d1dff8a7-8a89-4c8a-bd35-cf799a7bb4fb.png)

![camera buildin imu](https://user-images.githubusercontent.com/68782862/158758378-dab2e7ec-6489-436a-bb85-c684c106262d.png)

**Comment by lhthq** [comment]
I  ALSO  meet  this problem.  I  guess  this  extrinsic  is not  accurate.  What do  u  think of it?

**Comment by sjtuyinjie** [comment]
The coordination frame of VI-sensor is that x points to right, y points to down, z points to front. While the coordination frame of Handsfree is that x points to left, y points to front, z points to up.
