### ISSUE TITLE
红外相机和激光雷达是否进行联合标定了

### ISSUE THREAD

**Issue by DCYzhao** [SJTU-ViSYS/M2DGR#18]
目前在研究红外slam和激光融合，激光雷达可以提供深度信息，提高红外视觉的精度，

**Comment by sjtuyinjie** [comment]
由于传感器安装在车上，运动不充分，用kalibr标定的结果误差会非常大。因此外参是人工量取的，误差会在3cm以内。可以参照给出的外参链接，里面有红外和雷达的外参
