### ISSUE TITLE
handsfree IMU传感器测量初值（重力）问题

### ISSUE THREAD

**Issue by EnochPer** [SJTU-ViSYS/M2DGR#19]
您好，我在使用数据集lift04.bag的时候发现handsfree传感器在设备静止的时候测量的重力加速度约为[0.0, 0.15, 10
.05]， 总的加速度也超过了常见的9.81，请问这是什么原因呢？谢谢

**Comment by sjtuyinjie** [comment]
That's because Sequence lift04 was recorded in a lift which went upstairs. For more details, please read our paper.

**Comment by EnochPer** [comment]
谢谢您的回复。不过我的测量是在rosbag刚开始播放时的，也就是机器人还在大厅内并没开始移动，并没有进入电梯，因此加速度应该没有受到电梯的影响。

**Comment by sjtuyinjie** [comment]
这个问题，要不加我个人微信私聊？yj1195391308

**Comment by sjtuyinjie** [comment]
这个问题，要不加我个人微信私聊？yj1195391308
