### ISSUE TITLE
Can you provide more extrinsic information

### ISSUE THREAD

**Issue by wangyu-060070** [SJTU-ViSYS/M2DGR#2]
Such as camera-imu, thermal-imu extrinsic, thank you very much

**Comment by SJTU-ViSYS** [comment]
We are going to update the extrinsic files soon, please just wait for a few days.

**Comment by sjtuyinjie** [comment]
Actually, camera-imu extrinsic has already been given in the VINS-MONO configuration file. And thermal-imu extrinsic can be calculated with thermal-lidar and imu-lidar extrinsic
