### ISSUE TITLE
It would be better with raw wheel encoding data.

### ISSUE THREAD

**Issue by JaySlamer** [SJTU-ViSYS/M2DGR#20]
Due to no enough excitation of imu on planar motion and insane drift of accelerator integration when visual tracking is lost, a lot of indoor ground vehicle applications requires wheel encoders to be practical. I would appreciate it even more if your guys be so kind to add wheel encoding raw data into your already fantastic dataset.

**Comment by sjtuyinjie** [comment]
Thanks for your good advice! Actually, we are preparing for SLAM datasets with wheel encoders these days but our plans have been postponed by the Covid. We will release the data as soon as we are allowed to go to the lab. Keep following our work!
