### ISSUE TITLE
Camera Intrinsics and Extrinsics

### ISSUE THREAD

**Issue by matval** [SJTU-ViSYS/M2DGR#21]
Where can I find the cameras intrinsics and extrinsics?

Thank you

**Comment by sjtuyinjie** [comment]
https://github.com/SJTU-ViSYS/M2DGR/blob/main/calibration_results.txt

**Comment by sjtuyinjie** [comment]
Give us a star if you like this project!

**Comment by DrZ-21** [comment]
> https://github.com/SJTU-ViSYS/M2DGR/blob/main/calibration_results.txt

你好，我利用此文件的handfree到lidar的变换和d435RGB到lidar的变换得到handfreeimu到d435RGB的外参变换,好像和另一个文件lvi-sam里面的mycam.yaml里面的d435RGB到handfreeimu的变换的逆的平移量的第一维差个负号，不知道是我算错了还是哪个结果不太对呢？
