### ISSUE TITLE
GT consistency across sequences

### ISSUE THREAD

**Issue by cattaneod** [SJTU-ViSYS/M2DGR#23]
First of all, thank you for releasing this dataset.

I have an issue regarding the ground truth poses, I want to test an approach for inter-sequence LiDAR localization, i.e. localize a single scan from a sequence in a LiDAR map built from another sequence. However, when I try to visualize two point clouds of the same place taken from two different sequences using the provided GTs, the scan does not align precisely (see attached images). As it was not clear in which frame the GTs are expressed (GNSS? Lidar? IMU?) I also checked the extrinsic calibration provided (calibration_results.txt). However, all the extrinsic matrices have an identity rotation, thus the results is the same.

![image](https://user-images.githubusercontent.com/11426917/172374658-d096f3a7-076b-41c5-bc86-c2c2d18109b3.png)
![image](https://user-images.githubusercontent.com/11426917/172374680-50d67801-d077-4f45-b838-a10c6327bf5f.png)

**Comment by sjtuyinjie** [comment]
The ground truth comes from a GNSS-IMU suite, Xsens MTI 680G, which reports a 2cm localizatioin accuracy with good RTK signals.
I'd like to ask which sequences have you tested? Are they Street series? Maybe one of them were with bad GNSS signals, leading to a misalignment in trajectory.

**Comment by cattaneod** [comment]
I tried with sequences `street_02` and `street_06`
