### ISSUE TITLE
致敬你们的工作，为你们点赞

### ISSUE THREAD

**Issue by zm0612** [SJTU-ViSYS/M2DGR#27]
像这样完整、全面的用于机器人SLAM的数据集确实少有，非常开心看到你们做的工作，为你们点赞

**Comment by sjtuyinjie** [comment]
谢谢你的肯定！如果对其他数据有需求的话，欢迎提出宝贵的建议

**Comment by JixinGao** [comment]
非常希望能够加入轮式计的数据，目前SLAM有的带轮式计的非常少，少有几个带有轮式的，激光雷达又没有时间戳，也不是rosbag形式，不过您的数据集真的非常好用，感谢！

**Comment by sjtuyinjie** [comment]
欢迎关注我们的新工作https://github.com/sjtuyinjie/Ground-Challenge，里面包含了轮式里程计数据。喜欢的话可以点个star，谢谢~

**Comment by sjtuyinjie** [comment]
欢迎关注我们的新工作https://github.com/sjtuyinjie/Ground-Challenge，里面包含了轮式里程计数据。喜欢的话可以点个star，谢谢

**Comment by JixinGao** [comment]
> 欢迎关注我们的新工作[https://github.com/sjtuyinjie/Ground-Challenge，里面包含了轮式里程计数据。喜欢的话可以点个star，谢谢](https://github.com/sjtuyinjie/Ground-Challenge%EF%BC%8C%E9%87%8C%E9%9D%A2%E5%8C%85%E5%90%AB%E4%BA%86%E8%BD%AE%E5%BC%8F%E9%87%8C%E7%A8%8B%E8%AE%A1%E6%95%B0%E6%8D%AE%E3%80%82%E5%96%9C%E6%AC%A2%E7%9A%84%E8%AF%9D%E5%8F%AF%E4%BB%A5%E7%82%B9%E4%B8%AAstar%EF%BC%8C%E8%B0%A2%E8%B0%A2)
非常感谢！后续会进行测试，star咯!
