### ISSUE TITLE
The question about global-localization in SLAM

### ISSUE THREAD

**Issue by goldqiu** [SJTU-ViSYS/M2DGR#30]
Hi，
        Can this dateset be used for global localization？I mean that i want to re-localize anywhere in pre-build global map made by this dataset.
                                                                                                                                                                             Thank you

**Comment by sjtuyinjie** [comment]
Xsens 680G reports an accuracy of 2cm, so you can try your algorithm on outdoor sequences of M2DGR, like Street and Gate series. Wish you good luck.
