### ISSUE TITLE
Questions about Lidar-IIMU calib

### ISSUE THREAD

**Issue by TongxingJin** [SJTU-ViSYS/M2DGR#31]
Hi, thks for your nice work. For the extrinsic between Lidar and IMU, you refer to [Lidar_IMU_Calib], did it works well for ground vehicles without sufficient excitement? And in the livestream tonight, you said you have done some measurements manually, so what information did you adopt from Lidar_IMU_Calib?

**Comment by sjtuyinjie** [comment]
I once calibrated the extrinsic between Lidar and IMU using this work which  gave a bad result. I used to publish this result in the calibration_result.txt file, but I replace it with a more accurate one later.

**Comment by TongxingJin** [comment]
> I once calibrated the extrinsic between Lidar and IMU using this work which gave a bad result. I used to publish this result in the calibration_result.txt file, but I replace it with a more accurate one later.

And then how you get a more accurate one? by manual measurement?

**Comment by sjtuyinjie** [comment]
Right. This is the common method when calibration algorithms fail.
