### ISSUE TITLE
Camera topics in ros bag are compressed image format, it didn't correspond to the config file

### ISSUE THREAD

**Issue by tangxiangshi** [SJTU-ViSYS/M2DGR#35]
In config file both lvi-sam or vins-mono, the yaml file image topic are raw image which is sensor_msgs/image format. 

However in ros bag file, the camera image is  sensor_msgs/Compressedimage format.(I used rosbag info to test door_01, door_02, gate_01, room_01, room_dark01)

So the feature_tracker will not work, did the rosbag has been updated recently(which had been compressed)?

If you can give me the modified feature_tracker cpp file or the original ros bag. It would be a great help for me to test. 

You had done a great work, maybe my question is silly.

 
![image](https://user-images.githubusercontent.com/61973869/179775816-7a9f2e3b-3a89-4e55-9ac8-4bbed08d13e4.png)

**Comment by sp1keCHEN** [comment]
add
`<node pkg="image_transport" type="republish" name="image_republish" args="compressed in:=/camera/color/image_raw raw out:=/camera/color/image_raw" output="screen" respawn="true"/>`
in your launch file
