### ISSUE TITLE
gate_02真值有问题

### ISSUE THREAD

**Issue by sp1keCHEN** [SJTU-ViSYS/M2DGR#36]
真值80多秒处，进入了一个1m左右的坑，不管看图像还是跑算法，都不存在这么大的坑啊

**Comment by sjtuyinjie** [comment]
在大门下可能卫星信号短暂的被遮挡了，导致真值有些漂移。建议优先泡我论文里测评过的序列，那些肯定没问题

**Comment by wjf1997** [comment]
> 真值80多秒处，进入了一个1m左右的坑，不管看图像还是跑算法，都不存在这么大的坑啊

你好，我下载数据集的时候容易中断，请问有什么方法可以完整下载数据集吗

**Comment by sp1keCHEN** [comment]
> > 真值80多秒处，进入了一个1m左右的坑，不管看图像还是跑算法，都不存在这么大的坑啊
> 
> 你好，我下载数据集的时候容易中断，请问有什么方法可以完整下载数据集吗

https://gwliang.com/2020/05/26/linux-control-download-onedrive-files/
