### ISSUE TITLE
The Intrinsic Parameter for RGB Camera

### ISSUE THREAD

**Issue by zhehui-chen** [SJTU-ViSYS/M2DGR#37]
I want to run VINS-MONO with the RGB Camera and IMU, but the result is not good. It seems caused by the wrong camera parameter setting.

The config I use is like the following:
![Screenshot from 2022-07-28 16-59-20](https://user-images.githubusercontent.com/62113801/181465978-5bbb2f20-7055-4aa4-879c-c6637d1b00f9.png)

By the way, because the RGB Camera is a fish-eye lens with high FOV, so my camera model_type is MEI. The detailed intrinsic parameter and external parameter refers to [calibration_results.txt](https://github.com/SJTU-ViSYS/M2DGR/blob/main/calibration_results.txt).

Hope someone tell me if my config setting for camera is correct or not.

Thank you

**Comment by sjtuyinjie** [comment]
The handsfree imu is not hard-synced with the camera, which can lead to errors. For the VIO algorithm, it is recommended to use the realsense's IMU.
