### ISSUE TITLE
xsens mti的IMU数据似乎没有提供

### ISSUE THREAD

**Issue by wangyu-060070** [SJTU-ViSYS/M2DGR#4]

**Comment by sjtuyinjie** [comment]
As mentioned in my paper, the IMU infomation of XSENS is used for generating GT pose. If you need 9 axis IMU information for LiDAR SLAM, use the topic /handsfree/imu instead.

**Comment by wangyu-060070** [comment]
Figure 2 is mislabeled and there are two label-5. In addition, we calibrated the imu-camera extrinsic, the results show that the hander IMU is above the infrared

**Comment by sjtuyinjie** [comment]
Sorry, the left one of the "5" labels should be "7". But the handsfree IMU is below the infrared camera as shown in the figure.

**Comment by sjtuyinjie** [comment]
Maybe the IMU in the VI-sensor (Intel Realsense d435i) is above the infrared.

**Comment by wangyu-060070** [comment]
I utilize the Handsfree imu data, and the result shows that the IMU is above the infra camera

从 Windows 版邮件发送

发件人: Yin Jie
发送时间: 2021年12月30日 22:09
收件人: SJTU-ViSYS/M2DGR
抄送: Barrier; Author
主题: Re: [SJTU-ViSYS/M2DGR] xsens mti的IMU数据似乎没有提供 (Issue #4)

Maybe the IMU in the VI-sensor (Intel Realsense d435i) is above the infrared.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sjtuyinjie** [comment]
Please describe the detailed process how you got the this result.
