### ISSUE TITLE
请问有其他方法下载吗，这上边的链接一直失败

### ISSUE THREAD

**Issue by lvcm0201** [SJTU-ViSYS/M2DGR#42]

**Comment by sjtuyinjie** [comment]
如之前的issue里说过的，其他的网盘各有各的问题。目前只支持onedrive下载器。不好意思了

**Comment by wjf1997** [comment]
> _No description provided._

请问你现在下载成功了吗

**Comment by JixinGao** [comment]
多下载几次就好了，下载的时候确实容易中断，不过多点几次就可以成功了，我是这样的

**Comment by wjf1997** [comment]
> 多下载几次就好了，下载的时候确实容易中断，不过多点几次就可以成功了，我是这样的

比较小的文件这样能下载成功，但是七八十G大的文件就没法这样了，有其他办法吗
