### ISSUE TITLE
street_07的真实轨迹是不是有问题

### ISSUE THREAD

**Issue by chenhuahua-orz** [SJTU-ViSYS/M2DGR#45]
您好。我在用您的street07数据集跑LIO-SAM过程中发现　真实轨迹明显多出了一截（我已经把真实轨迹开始和结束多余的时间删除了）
![屏幕截图_1](https://user-images.githubusercontent.com/90565115/190896410-cb2628ee-861b-4eb6-a329-e717459ce331.png)

**Comment by chenhuahua-orz** [comment]
![屏幕截图_2](https://user-images.githubusercontent.com/90565115/190899777-fc039f7e-8554-4451-81c7-321458a61da7.png)

**Comment by sjtuyinjie** [comment]
可能这一段RTK的信号不良，导致轨迹出现了偏移。建议使用其他序列

**Comment by wjf1997** [comment]
> 

你好，我下载数据集的时候容易中断，请问有什么方法可以完整下载数据集吗
