### ISSUE TITLE
 The file LVISAM-modified.md mentioned the third paragraph that comment some code

### ISSUE THREAD

**Issue by wjf1997** [SJTU-ViSYS/M2DGR#46]
// Comment the following code
    
    // pcl::PointCloud<PointType>::Ptr laser_cloud_offset(new pcl::PointCloud<PointType>());
    // Eigen::Affine3f transOffset = pcl::getTransformation(L_C_TX, L_C_TY, L_C_TZ, L_C_RX, L_C_RY, L_C_RZ);
    // pcl::transformPointCloud(*laser_cloud_in, *laser_cloud_offset, transOffset);
    // *laser_cloud_in = *laser_cloud_offset;

As far as i concerned, it is not correct.
It aims to convert point cloud from lidar frame to IMU frame.

**Comment by sjtuyinjie** [comment]
Have no idea, either. Maybe you should ask the authors of the modified Lvi-sam
