### ISSUE TITLE
The ground truth of the sequence Street07 seems incorrect.

### ISSUE THREAD

**Issue by LvXudong-HIT** [SJTU-ViSYS/M2DGR#5]
![street07](https://user-images.githubusercontent.com/27817806/147846690-4c559029-fa92-42a4-a286-f5898cfb2afe.png)

**Comment by sjtuyinjie** [comment]
Yes，in our paper we manually removed the part with inaccurate RTK signals.

**Comment by sjtuyinjie** [comment]
Sorry for our oversight. You can delete the front part of the GT file when you evaluate your result with EVO toolbox.
