### ISSUE TITLE
关于GT

### ISSUE THREAD

**Issue by qqstar-423** [SJTU-ViSYS/M2DGR#51]
请问GT地面真值的单位是米还是公米呢，我使用以下matlab代码并未得到正确的LLA坐标系下的经纬度值，这是为什么呢
function [lat,lon,alt] = ecef2lla(x,y,z)

% WGS84 ellipsoid constants:
a = 6378137;
e = 8.1819190842622e-2;

b   = sqrt(a^2*(1-e^2));
ep  = sqrt((a^2-b^2)/b^2);
p   = sqrt(x.^2+y.^2);
th  = atan2(a*z,b*p);
lon = atan2(y,x);
lat = atan2((z+ep^2.*b.*sin(th).^3),(p-e^2.*a.*cos(th).^3));
N   = a./sqrt(1-e^2.*sin(lat).^2);
alt = p./cos(lat)-N;

% return lon in range [0,2*pi)
lon = mod(lon,2*pi);

k=abs(x)<1 & abs(y)<1;
alt(k) = abs(z(k))-b;

return

**Comment by sjtuyinjie** [comment]
单位是m。我记得我成功转过，但是时间太久远了，细节已经记不清楚了。可能需要你自己去推导一下
