### ISSUE TITLE
数据集下载问题

### ISSUE THREAD

**Issue by Liansheng-Wang** [SJTU-ViSYS/M2DGR#53]
OneDrive 上的数据包下载一点（20.3M）就提示完成了。你们有遇到过这个问题吗？

**Comment by sjtuyinjie** [comment]
最近下载确实出问题了。因为onedrive近期在国内不太稳定

**Comment by Liansheng-Wang** [comment]
可以提供一个百度网盘的下载链接吗？很需要你们的数据集




















在 2022-11-04 15:52:29，"Yin Jie" ***@***.***> 写道：

最近下载确实出问题了。因为onedrive近期在国内不太稳定

**Comment by Liansheng-Wang** [comment]
可以提供一个百度网盘的下载链接吗？很需要你们的数据集
