### ISSUE TITLE
Quaternion rotation jumps in MoCap data

### ISSUE THREAD

**Issue by adaruna3** [SJTU-ViSYS/M2DGR#54]
Hi,

Thank you for providing this dataset. I am interested in using the MoCap and IMU data for the indoor part of the dataset.

I have noticed that the MoCap data randomly experiences large jumps in values of the quaternion rotations. Are these errors due to the MoCap system? Or is there some sporadic gimbal lock phenomenon I should account for?

Once specific instance is on lines 150-165 of the ground truth data for `room_01.txt`. See the below lines in the screen shot:
![image](https://user-images.githubusercontent.com/21183560/199646671-42ff9e48-c46a-4087-9fff-f7099792addc.png)

This is not the only instance for that trajectory. There are many instances of such jumps in this trajectory as well as all trajectories using the MoCap for ground truth. Here I have plotted the positions of the MoCap frame and Realsense 435i IMU frame. You can see the MoCap frame (green) is steady while the Realsense 435i IMU frame (red) jumps randomly above and below the MoCap frame.
![mocap_no_filter_room_01](https://user-images.githubusercontent.com/21183560/199647008-6243fb0f-8e60-4f48-80b1-eacc96b8d611.png)

I am more certain this is not an error in my code. If I add a simple filter that removes the MoCap data which sporadically jumps using the following lines of code...
![image (1)](https://user-images.githubusercontent.com/21183560/199647167-81372ca3-908f-4965-adea-3d82dcf00f36.png)

... then the trajectories align well:
![mocap_with_filter_room_01_b](https://user-images.githubusercontent.com/21183560/199647948-952a04b3-30ed-49a6-afc8-e1adde0381b3.png)

Since I would prefer to keep these data points, is there some issue with the MoCap that you know of which I can account for this using a few lines of code? I am considering trying some guesses at 180 degree rotations until I find a close enough rotational alignment with the trajectory.

Thanks for your time and efforts!!
Angel

**Comment by sjtuyinjie** [comment]
Thanks for your comment. The mocap system sometimes might not track the robot well, leading to an abrupt change in quaternions. It is strongly recommended that you use a filter for more accurate data
