### ISSUE TITLE
下载速度超级慢

### ISSUE THREAD

**Issue by jxx315** [SJTU-ViSYS/M2DGR#58]
交大的同学好，

数据集做的很棒，是广大slam研究者的福音。  只是有一点，下载速度太慢太慢，  而且容易断掉。
建议可以放在百度云盘，或者其它较好的站点。 昨天折腾半天，一个文件都没下载成功。。

**Comment by heisetiantang** [comment]
同学你好，首先能肯定你们的数据集制作的非常出色，各种场景都有所覆盖，
但有些网络小问题
确实，并且中间不能出现网络波动，一旦出现就会出现下载中断，或者只下载一半的情况，并且不能将连接转到例如迅雷等下在工具中，无法识别

**Comment by sjtuyinjie** [comment]
这个问题非常抱歉，其他网盘我们也测试过，但是有各式各样的问题。如果下载实在很卡的话，建议弄个梯子
