### ISSUE TITLE
激光雷达的垂直方向的视角范围是否进行更改了呢，和默认值有所不同

### ISSUE THREAD

**Issue by heisetiantang** [SJTU-ViSYS/M2DGR#59]
VLP-32C默认的垂直方向的视角是-25度到+15度，同学的参数中写的是-30度到+10度，如果能附件各传感器的驱动和配套文件将会更好，例如每条线数的垂直方向角度
![2022-12-26 15-11-57 的屏幕截图](https://user-images.githubusercontent.com/92718554/209517236-457358d2-ee78-4203-af56-129f3d983f85.png)

**Comment by sjtuyinjie** [comment]
可能是个笔误，感谢指正
