### ISSUE TITLE
Speed up the downloading

### ISSUE THREAD

**Issue by yanming-zou** [SJTU-ViSYS/M2DGR#6]
Downloading directly from Onedrive is somewhat slow. Do you have any suggestions to speed up the downloading process?

**Comment by sjtuyinjie** [comment]
If you download on campus network, the speed of Onedrive will be like 10 MB/s. I've tried some other netdisks lick baidu netdisk, but the size of a single file is limited to 20 G, which is not enough for most of our dataset sequences. As for Google Drive and dropbox, it will be hard for Chinese users to access.
