### ISSUE TITLE
数据集中所提供的真值与Handsfree IMU（或其他传感器）间的外参转换是怎样的

### ISSUE THREAD

**Issue by qiaoqiaodefengle187** [SJTU-ViSYS/M2DGR#62]
非常感谢您提供这么全面的数据集，因为想进行姿态与真值的比较，所以想咨询一下 数据集中所提供的真值是表示的谁的位姿？它与Handsfree IMU（或其他传感器）间的外参转换是怎样的？

谢谢

**Comment by sjtuyinjie** [comment]
真值是xsens 680g的位姿或者莱卡棱镜的位姿。xsens与handsfree imu的旋转可以视作单位矩阵
