### ISSUE TITLE
校园网下载速度也很慢

### ISSUE THREAD

**Issue by nhjydywd** [SJTU-ViSYS/M2DGR#70]
感谢你们的工作，让国内终于也有靠谱的数据集了。

但是我用校园网下载只有300kb/s，完全达不到10MB/s。

可否考虑一下百度网盘？网盘svip1级就可以上传300G的单个文件，完全足以存储rosbag。

**Comment by sjtuyinjie** [comment]
非常抱歉，网盘的费用不太好报销。如果你急需的话，可以联系我的邮件，把硬盘寄过来我给你拷
