### ISSUE TITLE
可以从热图像中读取到物体的温度值吗

### ISSUE THREAD

**Issue by GaoTianyu1998** [SJTU-ViSYS/M2DGR#72]

**Comment by sjtuyinjie** [comment]
这个我也没研究过，应该是有个转换关系的。但是我手头没有数据

**Comment by GaoTianyu1998** [comment]
你好，我最近买了和你们数据集同款的热红外相机，并且使用了你们提供的驱动，请问用这个驱动采集到的红外图像是被压缩过的吗，因为我发现在ros下采集的图像质量没有厂家提供的在win下的sdk的图像质量好。

**Comment by DreamWaterFound** [comment]
> 你好，我最近买了和你们数据集同款的热红外相机，并且使用了你们提供的驱动，请问用这个驱动采集到的红外图像是被压缩过的吗，因为我发现在ros下采集的图像质量没有厂家提供的在win下的sdk的图像质量好。

也不一定是被压缩过的，一般来说热红外相机的图像都是 16bit 色深图像，但是你使用正常的图像工具查看的时候，通常都要先转换成为 8bit 色深图像进行显示，这个转换的方法会造成精度损失，也会影响屏幕直接显示出来的图像质量。
