### ISSUE TITLE
请问可以提供论文里面Fig.4使用的在ENU坐标系下的真值数据吗？

### ISSUE THREAD

**Issue by 404-ZILIANG** [SJTU-ViSYS/M2DGR#73]
您好，由于真值数据是ECEF坐标系下的，不好进行水平方向和竖直方向的漂移计算，麻烦能提供论文里面Fig.4使用的在ENU坐标系下的真值数据吗？我使用的数据是street系列的数据集。

**Comment by sjtuyinjie** [comment]
根据ecef坐标可以自己转enu，你可以去搜一下脚本

**Comment by 404-ZILIANG** [comment]
Hi!  Ziliang Li have received your email.  It will be checked in time.Good luck with your work~
