### ISSUE TITLE
rosbag play 时出现 required op field misiing 

### ISSUE THREAD

**Issue by studyboom** [SJTU-ViSYS/M2DGR#74]
很感谢你们为slam领域做出的贡献，这是一个十分全面的数据集。但在使用你们数据集时，遇到了一些小问题：rosbag play 时出现 required op field misiing ；使用rosbag reindex xx.bag 也不能完全修复，请问要怎么才可以避免该问题了？

**Comment by DreamWaterFound** [comment]
看这个报错，应该是文件传输错误导致的

**Comment by studyboom** [comment]
谢谢你的答复，我再去重新下载数据

**Comment by studyboom** [comment]
谢谢你的答复，我再去重新下载数据试试

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: 刘国庆, Guoqing ***@***.***>
发送时间: 2023年4月4日 9:24
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [SJTU-ViSYS/M2DGR] rosbag play 时出现 required op field misiing (Issue #74)


看这个报错，应该是文件传输错误导致的

―
