### ISSUE TITLE
请问可以提供一下鱼眼相机标定的数据，和鱼眼镜头的具体型号信息吗，谢谢

### ISSUE THREAD

**Issue by githubwys** [SJTU-ViSYS/M2DGR#76]
您好，我在进行测试的时候，想自己进行一下鱼眼相机标定等相关工作，希望能获取一下标定的原始数据。
此外，还想了解一下鱼眼镜头的型号，想知道FLIR Pointgrey CM3-U3-13Y3C-CS相机能做到190*190视野的镜头是什么，谢谢

**Comment by sjtuyinjie** [comment]
淘宝搜中联科创鱼眼镜头即可搜到
