### ISSUE TITLE
mti

### ISSUE THREAD

**Issue by ycl-web** [SJTU-ViSYS/M2DGR#77]
非常感谢您优秀的作品。我想问的是，您使用mti-680g时可以在ros环境中获得rtk纠正以后的经纬高信息吗。还是您在mtmanager软件中启用ntrip后进行记录的。您的groundtruth是使用imu+rtk进行耦合的吗？您如何保证和slam的时间同步呢？非常感谢您！

**Comment by SJTU-ViSYS** [comment]
ros环境下我尝试过硬触发，但是无奈并未成功，所以使用的是mtmanager。gt是算法耦合imu和rtk后的结果。时间戳的差异是经过标定的
