### ISSUE TITLE
你好,请问你们是如何将原始14bit红外图像转化为bag中的8bit的?

### ISSUE THREAD

**Issue by Adamqu199541** [SJTU-ViSYS/M2DGR#79]
你好,首先十分感谢您提供如此详实的工作,为你们点赞.   有个问题,一般来说,红外相机提供的都是14bit原始红外图像, 实际在用的时候是8bit图像,我看 你们的数据集提供的是8bit图像,那请问你们是如何转化的?

**Comment by SJTU-ViSYS** [comment]
我们用的是高德红外PLUG 617相机，在上位机里我们设置的就是8bit的格式
