### ISSUE TITLE
The sequence gate_03's GT seems wrong

### ISSUE THREAD

**Issue by zhaohaowu** [SJTU-ViSYS/M2DGR#8]
I used gate_03.bag to obtain a trajectory data and I found that my results were very different from the true value
Finally I found the data of gate_03.txt seems wrong where x, y and z value of gate_03.txt is several million meter

**Comment by sjtuyinjie** [comment]
Sorry, maybe I've uploaded the wrong GT file. I am busy these days, so I will upload the right one some time later.
