### ISSUE TITLE
What is the extrinsic of imu and gt (Leica) in hall data?

### ISSUE THREAD

**Issue by LTHlidar** [SJTU-ViSYS/M2DGR#84]
First, thank you for providing the dataset!

I am trying to compare GT and LiO-SAM pose results using hall data.

I would like to compare the pose results with respect to the IMU coordinate system.

So, can you give me the extrinsic between GT (Leica) and handsfree IMU?
For example, translational and rotational parameters.
Thanks.

**Comment by Alex-Beh** [comment]
Asking for the same question. Would like to know the extrinsic matrix so I can align the trajectories and calculate the absolute pose error. Do you manage to find out the answer?

**Comment by h-k8888** [comment]
Asking for the same question.
