### ISSUE TITLE
Why is the Image Topic in a Compressed Form？

### ISSUE THREAD

**Issue by kenan9875645** [SJTU-ViSYS/M2DGR#85]
"/camera/aligned_depth_to_color/image_raw/compressed
/camera/color/image_raw/compressed
/camera/fifth/image_raw/compressed
/camera/fourth/image_raw/compressed"

Above is the ros topic of room_01.bag file output.
How can I obtain the topic of /camera/color/image_raw/ from /camera/color/image_raw/compressed?

**Comment by DreamWaterFound** [comment]
Using compressed images can greatly reduce unnecessary bandwidth consumption and storage space usage. You can calculate how much bandwidth would be consumed if you were to directly publish and save the raw images, considering the number of image data channels.

If you need to fetch the original images, I recommend using the `image_transport` plugin. You can find specific methods and instructions [here](http://wiki.ros.org/image_transport). You can directly write code in your program to call the `image_transport` API, or you can use `image_transport`'s command-line tools to republish the compressed images as original images.
