### ISSUE TITLE
LVI-SAM中的激光-IMU平移外参是不是给反了？

### ISSUE THREAD

**Issue by 504115681** [SJTU-ViSYS/M2DGR#86]
LVI-SAM的params_lidar.yaml文件中，extrinsicRot和extrinsicTrans表示将IMU坐标系转换到激光坐标系的旋转和平移外参，以激光雷达为参考坐标系。从下图中可以看出，如果以激光雷达（3）为参考坐标系，IMU（5）原点位置应该是：[负数,接近0,负数]，而提供的平移外参为：[0.27255, -0.00053,0.17954]，是不是应该改为：[-0.27255, 0.00053,-0.17954]？
![image](https://github.com/SJTU-ViSYS/M2DGR/assets/55040440/ae312491-454c-4b16-9790-4cb0cb7a45f7)

**Comment by G4419** [comment]
我感觉好像也是反的
