### ISSUE TITLE
Velodyne points have negative time stamps?

### ISSUE THREAD

**Issue by brytsknguyen** [SJTU-ViSYS/M2DGR#87]
Hi 

I suppose the correct pcl definition for the pointcloud would be as follows:
https://github.com/TixiaoShan/LVI-SAM/blob/0d822f6dcac3378312f6703b4f45829e049f221a/src/lidar_odometry/imageProjection.cpp#L5

When I print out the time stamp of the points, their values are negative:
![image](https://github.com/SJTU-ViSYS/M2DGR/assets/13504903/4a01962e-abdc-4e0c-ac6a-025c30f2a3a3)

This is a little bit surprising since I mostly encounter data with positive timestamps of the points.

Should the timestamp be the actual offset from pointcloud2 msg timestamp?

**Comment by sjtuyinjie** [comment]
Thanks for answering.
