### ISSUE TITLE
Handsfree A9 IMU与雷达的时间同步问题

### ISSUE THREAD

**Issue by YWL0720** [SJTU-ViSYS/M2DGR#88]
感谢你们的工作！有一个疑问想要请教一下。论文中提到了数据集所用传感器之间的时间同步方式，是采用同一系统时间。我了解到Handsfree A9所提供的接口有限，想请问一下，Handsfree A9和激光雷达等传感器具体是如何进行时间同步的，是ptp之类的方法么？目前我也遇到了这方面的需求，希望能得到一些建议。感谢您的回复！

**Comment by sjtuyinjie** [comment]
事实上这一块处理得不够严谨，确实应该使用ptp等方式同步。
