### ISSUE TITLE
关于数据集下载的问题

### ISSUE THREAD

**Issue by songhongxuan** [SJTU-ViSYS/M2DGR#91]
您好，感谢您为SLAM开源社区所做的工作，请问是否方便提供百度网盘的下载连接，通过README中所提供的链接经常会出现下载中断的现象，根据之前所介绍的使用校园网进行下载速度依旧是几kb左右，如果可以十分感谢！

**Comment by sjtuyinjie** [comment]
网盘网盘会限制bag大小，无法上传。我尝试过google drive，dropbox，阿里云盘等，都不太好用，很抱歉
