### ISSUE TITLE
如何从ublox  ZED-f9p中获得GNSS原始量测

### ISSUE THREAD

**Issue by homra29** [SJTU-ViSYS/M2DGR#94]
感谢您做出的无私贡献，我的问题是：如何从ublox  ZED-f9p中获得GNSS原始量测，并将其转化成rostopic。

**Comment by sjtuyinjie** [comment]
https://github.com/HKUST-Aerial-Robotics/ublox_driver
用这个驱动即可，亲测有效
好用的话请给M2FGR点个赞，感谢~
