### ISSUE TITLE
config_files

### ISSUE THREAD

**Issue by liliang2655** [SJTU-ViSYS/M2DGR#97]
大佬您好，非常感谢您的工作。（一直在找一个靠谱的复杂场景数据集）
有个问题，您用的V-I Sensor**,Realsense d435i，好像没有给深度信息和imu内外参。在之前您的回答里看到，您是没有录深度话题。

但是您给的paperd435i.yaml里没有imu内参以及imu到相机之间的外参。

csdn上关于orb3里，也是用的外置imu，也就是说，您这里是把d435i当成单目相机来用吗？求指点，感谢！

**Comment by sjtuyinjie** [comment]
内外参在这里：https://github.com/SJTU-ViSYS/M2DGR/blob/main/calibration_results.txt
