### ISSUE TITLE
轨迹真值

### ISSUE THREAD

**Issue by liaoshuichang** [SJTU-ViSYS/M2DGR#98]
如果我想用evo对比算法轨迹和真值，真值应该用哪个话题？谢谢！

**Comment by liaoshuichang** [comment]
发布的/ublox都只有1hz，我要如何得到轨迹真值呢

**Comment by sjtuyinjie** [comment]
在github主页里有gt，你看看

**Comment by repeeeeeat** [comment]
您提供的GT是在ecef坐标系？那我要怎样转到enu坐标系呢？您提供的/ublox只有1
hz
